apiVersion: v1
kind: Secret
metadata:
  name: mydockerkey
  namespace: default
data:
  .dockercfg: eyJ5dXd6aG9hY3IuYXp1cmVjci5pbyI6eyJwYXNzd29yZCI6Ij1zZ1dGPS8xOFpTYXdFL1VtMFVFS1dacFF3bU4wSHpwIiwiZW1haWwiOiJ5dXd6aG9AbWljcm9zb2Z0LmNvbSIsInVzZXJuYW1lIjoieXV3emhvYWNyIn19
type: kubernetes.io/dockercfg
